#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get install -y nginx
echo "Hello World!" > /etc/nginx/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/randomal permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /ect/nginx/sites-enabled/default
sudo service nginx restart
